#!/usr/bin/env php
<?php

$stderr = fopen('php://stderr', 'w');

require dirname(__FILE__) . '/Packager/packager.php';

$executable = array_shift($argv);
$package = dirname(__FILE__);

$pkg = new Packager($package);

fwrite($stderr, "Packager is building MooTools More\n\n");
fwrite($stderr, "Included Components:\n");


$files = (empty($argv)) ? $pkg->get_all_files() : $pkg->components_to_files($argv);

$files = $pkg->complete_files($files);

foreach ($files as $file){
	fwrite($stderr, "- $file: [" . implode(", ", $pkg->get_file_provides($file)) . "]\n");
}

$output = $pkg->build($files);

echo $output;

fclose($stderr);

?>
