name: "More"

exports: "mootools-more.js"

web: "[mootools.net](http://mootools.net)"

description: "MooTools Plugins and Enhancements Repository"

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; [MooTools](http://mootools.net)"

authors: "[The MooTools development team](http://mootools.net/developers)"

version: "1.3-wip"

sources:
  - "Source/Core/More.js"
  - "Source/Core/Log.js"
  - "Source/Class/Events.Pseudos.js"
  - "Source/Class/Class.Refactor.js"
  - "Source/Class/Class.Binds.js"
  - "Source/Class/Class.Occlude.js"
  - "Source/Class/Chain.Wait.js"
  - "Source/Types/Array.Extras.js"
  - "Source/Types/Date.js"
  - "Source/Types/Date.Extras.js"
  - "Source/Types/Object.Extras.js"
  - "Source/Types/String.Extras.js"
  - "Source/Types/String.QueryString.js"
  - "Source/Types/URI.js"
  - "Source/Types/URI.Relative.js"
  - "Source/Types/Hash.js"
  - "Source/Types/Hash.Extras.js"
  - "Source/Element/Element.Forms.js"
  - "Source/Element/Elements.From.js"
  - "Source/Element/Element.Pseudos.js"
  - "Source/Element/Element.Delegation.js"
  - "Source/Element/Element.Measure.js"
  - "Source/Element/Element.Pin.js"
  - "Source/Element/Element.Position.js"
  - "Source/Element/Element.Shortcuts.js"
  - "Source/Forms/Form.Request.js"
  - "Source/Forms/Form.Request.Append.js"
  - "Source/Forms/Form.Validator.js"
  - "Source/Forms/Form.Validator.Inline.js"
  - "Source/Forms/Form.Validator.Extras.js"
  - "Source/Forms/OverText.js"
  - "Source/Fx/Fx.Elements.js"
  - "Source/Fx/Fx.Accordion.js"
  - "Source/Fx/Fx.Move.js"
  - "Source/Fx/Fx.Reveal.js"
  - "Source/Fx/Fx.Scroll.js"
  - "Source/Fx/Fx.Slide.js"
  - "Source/Fx/Fx.SmoothScroll.js"
  - "Source/Fx/Fx.Sort.js"
  - "Source/Drag/Drag.js"
  - "Source/Drag/Drag.Move.js"
  - "Source/Drag/Slider.js"
  - "Source/Drag/Sortables.js"
  - "Source/Request/Request.JSONP.js"
  - "Source/Request/Request.Queue.js"
  - "Source/Request/Request.Periodical.js"
  - "Source/Utilities/Assets.js"
  - "Source/Utilities/Color.js"
  - "Source/Utilities/Group.js"
  - "Source/Utilities/Hash.Cookie.js"
  - "Source/Utilities/IframeShim.js"
  - "Source/Interface/HtmlTable.js"
  - "Source/Interface/HtmlTable.Zebra.js"
  - "Source/Interface/HtmlTable.Sort.js"
  - "Source/Interface/HtmlTable.Select.js"
  - "Source/Interface/Keyboard.js"
  - "Source/Interface/Keyboard.Extras.js"
  - "Source/Interface/Mask.js"
  - "Source/Interface/Scroller.js"
  - "Source/Interface/Tips.js"
  - "Source/Interface/Spinner.js"
  - "Source/Locale/Locale.js"
  - "Source/Locale/Date.English.US.js"
  - "Source/Locale/Form.Validator.English.js"
  - "Source/Locale/Date.Arabic.js"
  - "Source/Locale/Date.Catalan.js"
  - "Source/Locale/Date.Chinese.js"
  - "Source/Locale/Date.Czech.js"
  - "Source/Locale/Date.Danish.js"
  - "Source/Locale/Date.Dutch.js"
  - "Source/Locale/Date.English.GB.js"
  - "Source/Locale/Date.Estonian.js"
  - "Source/Locale/Date.French.js"
  - "Source/Locale/Date.German.js"
  - "Source/Locale/Date.German.CH.js"
  - "Source/Locale/Date.Hungarian.js"
  - "Source/Locale/Date.Italian.js"
  - "Source/Locale/Date.Japanese.js"
  - "Source/Locale/Date.Norwegian.js"
  - "Source/Locale/Date.Persian.js"
  - "Source/Locale/Date.Polish.js"
  - "Source/Locale/Date.Portuguese.js"
  - "Source/Locale/Date.Portuguese.BR.js"
  - "Source/Locale/Date.Russian.js"
  - "Source/Locale/Date.Slovenian.js"
  - "Source/Locale/Date.Spanish.js"
  - "Source/Locale/Date.Spanish.AR.js"
  - "Source/Locale/Date.Swedish.js"
  - "Source/Locale/Date.Ukrainian.js"
  - "Source/Locale/Form.Validator.Arabic.js"
  - "Source/Locale/Form.Validator.Catalan.js"
  - "Source/Locale/Form.Validator.Chinese.js"
  - "Source/Locale/Form.Validator.Czech.js"
  - "Source/Locale/Form.Validator.Danish.js"
  - "Source/Locale/Form.Validator.Dutch.js"
  - "Source/Locale/Form.Validator.Estonian.js"
  - "Source/Locale/Form.Validator.French.js"
  - "Source/Locale/Form.Validator.German.CH.js"
  - "Source/Locale/Form.Validator.German.js"
  - "Source/Locale/Form.Validator.Hungarian.js"
  - "Source/Locale/Form.Validator.Italian.js"
  - "Source/Locale/Form.Validator.Japanese.js"
  - "Source/Locale/Form.Validator.Norwegian.js"
  - "Source/Locale/Form.Validator.Persian.js"
  - "Source/Locale/Form.Validator.Polish.js"
  - "Source/Locale/Form.Validator.Portuguese.js"
  - "Source/Locale/Form.Validator.Portuguese.BR.js"
  - "Source/Locale/Form.Validator.Russian.js"
  - "Source/Locale/Form.Validator.Slovenian.js"
  - "Source/Locale/Form.Validator.Spanish.js"
  - "Source/Locale/Form.Validator.Spanish.AR.js"
  - "Source/Locale/Form.Validator.Swedish.js"
  - "Source/Locale/Form.Validator.Ukrainian.js"
