name: "More"

exports: "mootools-more.js"

web: "[mootools.net](http://mootools.net)"

description: "MooTools Plugins and Enhancements Repository"

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; [MooTools](http://mootools.net)"

authors: "[The MooTools development team](http://mootools.net/developers)"

version: "1.3-wip"

sources:
  - "Source/More/More.js"
  - "Source/Class/Events.Pseudos.js"
  - "Source/Class/Class.Refactor.js"
  - "Source/Class/Class.Binds.js"
  - "Source/Class/Class.Occlude.js"
  - "Source/Class/Chain.Wait.js"
  - "Source/Types/Array.Extras.js"
  - "Source/Types/Date.js"
  - "Source/Types/Date.Extras.js"
  - "Source/Types/Number.Format.js"
  - "Source/Types/Object.Extras.js"
  - "Source/Types/String.Extras.js"
  - "Source/Types/String.QueryString.js"
  - "Source/Types/URI.js"
  - "Source/Types/URI.Relative.js"
  - "Source/Types/Hash.js"
  - "Source/Types/Hash.Extras.js"
  - "Source/Element/Element.Forms.js"
  - "Source/Element/Elements.From.js"
  - "Source/Element/Element.Event.Pseudos.js"
  - "Source/Element/Element.Event.Pseudos.Keys.js"
  - "Source/Element/Element.Measure.js"
  - "Source/Element/Element.Pin.js"
  - "Source/Element/Element.Position.js"
  - "Source/Element/Element.Shortcuts.js"
  - "Source/Forms/Form.Request.js"
  - "Source/Forms/Form.Request.Append.js"
  - "Source/Forms/Form.Validator.js"
  - "Source/Forms/Form.Validator.Inline.js"
  - "Source/Forms/Form.Validator.Extras.js"
  - "Source/Forms/OverText.js"
  - "Source/Fx/Fx.Elements.js"
  - "Source/Fx/Fx.Accordion.js"
  - "Source/Fx/Fx.Move.js"
  - "Source/Fx/Fx.Reveal.js"
  - "Source/Fx/Fx.Scroll.js"
  - "Source/Fx/Fx.Slide.js"
  - "Source/Fx/Fx.SmoothScroll.js"
  - "Source/Fx/Fx.Sort.js"
  - "Source/Drag/Drag.js"
  - "Source/Drag/Drag.Move.js"
  - "Source/Drag/Slider.js"
  - "Source/Drag/Sortables.js"
  - "Source/Request/Request.JSONP.js"
  - "Source/Request/Request.Queue.js"
  - "Source/Request/Request.Periodical.js"
  - "Source/Utilities/Assets.js"
  - "Source/Utilities/Color.js"
  - "Source/Utilities/Group.js"
  - "Source/Utilities/Hash.Cookie.js"
  - "Source/Utilities/IframeShim.js"
  - "Source/Utilities/Table.js"
  - "Source/Utilities/Swiff.js"
  - "Source/Interface/HtmlTable.js"
  - "Source/Interface/HtmlTable.Zebra.js"
  - "Source/Interface/HtmlTable.Sort.js"
  - "Source/Interface/HtmlTable.Select.js"
  - "Source/Interface/Keyboard.js"
  - "Source/Interface/Keyboard.Extras.js"
  - "Source/Interface/Mask.js"
  - "Source/Interface/Scroller.js"
  - "Source/Interface/Tips.js"
  - "Source/Interface/Spinner.js"
  - "Source/Locale/Locale.js"
  - "Source/Locale/Locale.Set.From.js"
  - "Source/Locale/Locale.en-US.Date.js"
  - "Source/Locale/Locale.en-US.Form.Validator.js"
  - "Source/Locale/Locale.en-US.Number.js"
  - "Source/Locale/Locale.ar.Date.js"
  - "Source/Locale/Locale.ar.Form.Validator.js"
  - "Source/Locale/Locale.ca-CA.Date.js"
  - "Source/Locale/Locale.ca-CA.Form.Validator.js"
  - "Source/Locale/Locale.cs-CZ.Date.js"
  - "Source/Locale/Locale.cs-CZ.Form.Validator.js"
  - "Source/Locale/Locale.da-DK.Date.js"
  - "Source/Locale/Locale.da-DK.Form.Validator.js"
  - "Source/Locale/Locale.de-CH.Date.js"
  - "Source/Locale/Locale.de-CH.Form.Validator.js"
  - "Source/Locale/Locale.de-DE.Date.js"
  - "Source/Locale/Locale.de-DE.Form.Validator.js"
  - "Source/Locale/Locale.de-DE.Number.js"
  - "Source/Locale/Locale.en-GB.Date.js"
  - "Source/Locale/Locale.es-AR.Date.js"
  - "Source/Locale/Locale.es-AR.Form.Validator.js"
  - "Source/Locale/Locale.es-ES.Date.js"
  - "Source/Locale/Locale.es-ES.Form.Validator.js"
  - "Source/Locale/Locale.et-EE.Date.js"
  - "Source/Locale/Locale.et-EE.Form.Validator.js"
  - "Source/Locale/Locale.EU.Number.js"
  - "Source/Locale/Locale.fa.Date.js"
  - "Source/Locale/Locale.fa.Form.Validator.js"
  - "Source/Locale/Locale.fi-FI.Date.js"
  - "Source/Locale/Locale.fi-FI.Form.Validator.js"
  - "Source/Locale/Locale.fi-FI.Number.js"
  - "Source/Locale/Locale.fr-FR.Date.js"
  - "Source/Locale/Locale.fr-FR.Form.Validator.js"
  - "Source/Locale/Locale.fr-FR.Number.js"
  - "Source/Locale/Locale.he-IL.Date.js"
  - "Source/Locale/Locale.he-IL.Form.Validator.js"
  - "Source/Locale/Locale.he-IL.Number.js"
  - "Source/Locale/Locale.hu-HU.Date.js"
  - "Source/Locale/Locale.hu-HU.Form.Validator.js"
  - "Source/Locale/Locale.it-IT.Date.js"
  - "Source/Locale/Locale.it-IT.Form.Validator.js"
  - "Source/Locale/Locale.ja-JP.Date.js"
  - "Source/Locale/Locale.ja-JP.Form.Validator.js"
  - "Source/Locale/Locale.ja-JP.Number.js"
  - "Source/Locale/Locale.nl-NL.Date.js"
  - "Source/Locale/Locale.nl-NL.Form.Validator.js"
  - "Source/Locale/Locale.nl-NL.Number.js"
  - "Source/Locale/Locale.no-NO.Date.js"
  - "Source/Locale/Locale.no-NO.Form.Validator.js"
  - "Source/Locale/Locale.pl-PL.Date.js"
  - "Source/Locale/Locale.pl-PL.Form.Validator.js"
  - "Source/Locale/Locale.pt-BR.Date.js"
  - "Source/Locale/Locale.pt-BR.Form.Validator.js"
  - "Source/Locale/Locale.pt-PT.Date.js"
  - "Source/Locale/Locale.pt-PT.Form.Validator.js"
  - "Source/Locale/Locale.ru-RU.Date.js"
  - "Source/Locale/Locale.ru-RU.Form.Validator.js"
  - "Source/Locale/Locale.sl-SI.Date.js"
  - "Source/Locale/Locale.sl-SI.Form.Validator.js"
  - "Source/Locale/Locale.sv-SE.Date.js"
  - "Source/Locale/Locale.sv-SE.Form.Validator.js"
  - "Source/Locale/Locale.uk-UA.Date.js"
  - "Source/Locale/Locale.uk-UA.Form.Validator.js"
  - "Source/Locale/Locale.zh-CH.Date.js"
  - "Source/Locale/Locale.zh-CH.Form.Validator.js"
