name: "More-Tests"

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; [MooTools](http://mootools.net)"

authors: "[The MooTools development team](http://mootools.net/developers)"

sources:
  - "1.3/Class/Events.Pseudos.js"
  - "1.3/Class/Class.Refactor.js"
  - "1.3/Class/Class.Binds.js"
  - "1.3/Class/Class.Occlude.js"
  - "1.3/Class/Chain.Wait.js"
  - "1.3/Types/Array.Extras.js"
  - "1.3/Types/Date.js"
  - "1.3/Types/Date.Extras.js"
  - "1.3/Types/Number.Format.js"
  - "1.3/Types/Object.Extras.js"
  - "1.3/Types/String.Extras.js"
  - "1.3/Types/String.QueryString.js"
  - "1.3/Types/URI.js"
  - "1.3/Types/URI.Relative.js"
  - "1.3/Types/Hash.js"
  - "1.3/Types/Hash.Extras.js"
  - "1.3/Element/Element.Forms.js"
  - "1.3/Element/Elements.From.js"
  - "1.3/Element/Element.Event.Pseudos.js"
  - "1.3/Element/Element.Event.Pseudos.Keys.js"
  - "1.3/Element/Element.Delegation.js"
  - "1.3/Element/Element.Measure.js"
  - "1.3/Element/Element.Pin.js"
  - "1.3/Element/Element.Position.js"
  - "1.3/Element/Element.Shortcuts.js"
  - "1.3/Forms/Form.Validator.js"
  - "1.3/Fx/Fx.Reveal.js"
  - "1.3/Request/Request.JSONP.js"
  - "1.3/Utilities/Assets.js"
  - "1.3/Utilities/Color.js"
  - "1.3/Utilities/Group.js"
  - "1.3/Utilities/Hash.Cookie.js"
  - "1.3/Utilities/Table.js"
  - "1.3/Interface/HtmlTable.js"
  - "1.3/Interface/HtmlTable.Sort.js"
  - "1.3/Interface/HtmlTable.Select.js"
  - "1.3/Interface/Keyboard.js"
  - "1.3/Locale/Locale.js"
